<?php

namespace App\Constants\ActivityLog;

class ActivitiesConstants
{
    const WASTE_DISPOSAL_ACCEPTED = "WASTE_DISPOSAL_ACCEPTED";
    const WASTE_DISPOSAL_DECLINED = "WASTE_DISPOSAL_DECLINED";
    const WASTE_DISPOSAL_ARCHIVED = "WASTE_DISPOSAL_ARCHIVED";
    const CLIENT_CREATION = "CLIENT_CREATION";
    const UPDATED_CLIENT_STATUS = "UPDATED_CLIENT_STATUS";
    const DELETED_CLIENT = "DELETED_CLIENT";
    const ADMIN_CREATION = "ADMIN_CREATION";
    const ADMIN_UPDATE = "ADMIN_UPDATE";
    const UPDATED_ADMIN_STATUS = "UPDATED_ADMIN_STATUS";
    const CREATION_OF_WASTE_DISPOSAL_REQUEST = "CREATION_OF_WASTE_DISPOSAL_REQUEST";
    const UPLOADING_OF_ACCEPTANCE_SIGNATURE = "UPLOADING_OF_ACCEPTANCE_SIGNATURE";
    const UPLOADING_OF_TRANSPORT_MANIFEST = "UPLOADING_OF_TRANSPORT_MANIFEST";
    const CREATION_OF_INVOICE = "CREATION_OF_INVOICE";
    const CREATION_OF_LAB_REPORT = "CREATION_OF_LAB_REPORT";
    const UPDATED_LAB_REPORT = "UPDATED_LAB_REPORT";
    const ESCALATED_LAB_REPORT = "ESCALATED_LAB_REPORT";
    const CREATION_OF_WASTE_CERTIFICATE = "CREATION_OF_WASTE_CERTIFICATE";
    const UPLOADING_OF_PAYMENT_RECEIPT = "UPLOADING_OF_PAYMENT_RECEIPT";
    const APPROVAL_OF_FINAL_INVOICE = "APPROVAL_OF_FINAL_INVOICE";
    const UPDATING_OF_PAYMENT_RECEIPT = "UPDATING_OF_PAYMENT_RECEIPT";
    const COMPLETION_OF_DISPOSAL_REQUEST = "COMPLETION_OF_DISPOSAL_REQUEST";

    const STRIKED_USER = "STRIKED_USER";
    const BANNED_USER = "BANNED_USER";
    const SUSPEND_USER = "SUSPEND_USER";
    const DELETED_USER = "DELETED_USER";
    const HIDE_USER_POST = "HIDE_USER_POST";
    const RESTORE_USER_POST = "RESTORE_USER_POST";
    const DELETE_USER_POST = "DELETE_USER_POST";
    const ERASED_USER_DATA = "ERASED_USER_DATA";
    const DELETED_USER_ACCOUNT = "DELETED_USER_ACCOUNT";
    const CREATED_USER_ACCOUNT = "CREATED_USER_ACCOUNT";
    const UPDATED_USER_ACCOUNT = "UPDATED_USER_ACCOUNT";

    const CATEGORY_CREATED = "CATEGORY_CREATED";
    const CATEGORY_UPDATED = "CATEGORY_UPDATED ";
    const CATEGORY_DELETED = "CATEGORY_DELETED";

    const GUIDELINE_CREATED = "GUIDELINE_CREATED";
    const GUIDELINE_UPDATED = "GUIDELINE_UPDATED ";
    const GUIDELINE_DELETED = "GUIDELINE_DELETED";

    const SENT_USER_NOTIFICATION = "SENT_USER_NOTIFICATION";
    const CREATED_USER_NOTIFICATION  = "CREATED_USER_NOTIFICATION";
    const UPDATED_USER_NOTIFICATION  = "UPDATED_USER_NOTIFICATION";
    const DELETED_USER_NOTIFICATION  = "DELETED_USER_NOTIFICATION";

    const ANNOUNCEMENT_CREATED = "ANNOUNCEMENT_CREATED";
    const ANNOUNCEMENT_UPDATED  = "ANNOUNCEMENT_UPDATED ";
    const ANNOUNCEMENT_DELETED  = "ANNOUNCEMENT_DELETED";

    const GROUP_ACTIVATED = "GROUP_ACTIVATED";
    const GROUP_BANNED  = "GROUP_BANNED";
    const GROUP_SUSPENDED  = "GROUP_SUSPENDED";
    const GROUP_DELETED  = "GROUP_DELETED";

    const GROUP_MEMBER_ACTIVATED = "GROUP_MEMBER_ACTIVATED";
    const GROUP_MEMBER_BANNED  = "GROUP_MEMBER_BANNED";
    const GROUP_MEMBER_SUSPENDED  = "GROUP_MEMBER_SUSPENDED";

    const RESOLVED_REPORTED_COMMENT = "RESOLVED_REPORTED_COMMENT";
    const DELETED_REPORTED_COMMENT  = "DELETED_REPORTED_COMMENT";

    const RESOLVED_REPORTED_POST = "RESOLVED_REPORTED_POST";
    const DELETED_REPORTED_POST  = "DELETED_REPORTED_POST";

    const CREATED_TERMS_AND_CONDITION = "CREATED_TERMS_AND_CONDITION";
    const UPDATED_TERMS_AND_CONDITION  = "UPDATED_TERMS_AND_CONDITION";

    const CREATED_PRIVACY_POLICY = "PRIVACY_POLICY";
    const UPDATED_PRIVACY_POLICY  = "UPDATED_PRIVACY_POLICY";

    const CREATED_FAQ = "CREATED_FAQ";
    const UPDATED_FAQ  = "UPDATED_FAQ";

    const CREATED_FAQ_CATEGORY = "CREATED_FAQ_CATEGORY";
    const UPDATED_FAQ_CATEGORY  = "UPDATED_FAQ_CATEGORY";

    const CREATED_AVATAR = "CREATED_AVATAR";
    const UPDATED_AVATAR  = "UPDATED_AVATAR";
    const DELETED_AVATAR  = "DELETED_AVATAR";

    const CREATED_ROLE = "CREATED_ROLE";
    const UPDATED_ROLE  = "UPDATED_ROLE";
    const DELETED_ROLE  = "DELETED_ROLE";

    const CREATED_PERMISSION = "CREATED_PERMISSION";
    const UPDATED_PERMISSION  = "UPDATED_PERMISSION";
    const DELETED_PERMISSION  = "DELETED_PERMISSION";
 
}
