<?php

namespace App\Constants\ActivityLog;

class ActivitiesConstants
{
    const WASTE_DISPOSAL_ACCEPTED = "WASTE_DISPOSAL_ACCEPTED";
    const WASTE_DISPOSAL_DECLINED = "WASTE_DISPOSAL_DECLINED";
    const WASTE_DISPOSAL_ARCHIVED = "WASTE_DISPOSAL_ARCHIVED";
    const CLIENT_CREATION = "CLIENT_CREATION";
    const UPDATED_CLIENT_STATUS = "UPDATED_CLIENT_STATUS";
    const DELETED_CLIENT = "DELETED_CLIENT";
    const ADMIN_CREATION = "ADMIN_CREATION";
    const ADMIN_UPDATE = "ADMIN_UPDATE";
    const UPDATED_ADMIN_STATUS = "UPDATED_ADMIN_STATUS";
    const CREATION_OF_WASTE_DISPOSAL_REQUEST = "CREATION_OF_WASTE_DISPOSAL_REQUEST";
    const UPLOADING_OF_ACCEPTANCE_SIGNATURE = "UPLOADING_OF_ACCEPTANCE_SIGNATURE";
    const UPLOADING_OF_TRANSPORT_MANIFEST = "UPLOADING_OF_TRANSPORT_MANIFEST";
    const CREATION_OF_INVOICE = "CREATION_OF_INVOICE";
    const CREATION_OF_LAB_REPORT = "CREATION_OF_LAB_REPORT";
    const UPDATED_LAB_REPORT = "UPDATED_LAB_REPORT";
    const ESCALATED_LAB_REPORT = "ESCALATED_LAB_REPORT";
    const CREATION_OF_WASTE_CERTIFICATE = "CREATION_OF_WASTE_CERTIFICATE";
    const UPLOADING_OF_PAYMENT_RECEIPT = "UPLOADING_OF_PAYMENT_RECEIPT";
    const APPROVAL_OF_FINAL_INVOICE = "APPROVAL_OF_FINAL_INVOICE";
    const UPDATING_OF_PAYMENT_RECEIPT = "UPDATING_OF_PAYMENT_RECEIPT";
    const COMPLETION_OF_DISPOSAL_REQUEST = "COMPLETION_OF_DISPOSAL_REQUEST";

    const STRIKED_USER = "STRIKED_USER";
    const SUSPEND_USER = "SUSPEND_USER";
    const DELETED_USER = "DELETED_USER";
    const HIDE_USER_POST = "HIDE_USER_POST";


}

